### ISSUE TITLE
Web browser compatibility

### ISSUE THREAD

**Issue by Ekristoffe** [tnentwig/WebVisu#2]
Hello,
I am testing your system in an WAGO PLC (750-881)
I have different result with different web browser:

Internet explorer display nothing and in the console there is:
``` 
HTML1300: Navigation occurred.
webvisu.html
```

Google Chrome display the visu and in the console there is:
```
DevTools failed to load SourceMap: Could not load content for http://192.168.1.5/plc/WebVisu.dev.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
WebVisu.dev.js:60 GET http://192.168.1.5/visu_ini.xml 404 (Not Found)
(anonymous) @ WebVisu.dev.js:60
e.pathConfiguration @ WebVisu.dev.js:60
(anonymous) @ WebVisu.dev.js:60
(anonymous) @ WebVisu.dev.js:60
(anonymous) @ WebVisu.dev.js:60
(anonymous) @ WebVisu.dev.js:60
o @ WebVisu.dev.js:60
e.showMainVisu @ WebVisu.dev.js:60
(anonymous) @ WebVisu.dev.js:60
n @ WebVisu.dev.js:1
(anonymous) @ WebVisu.dev.js:1
(anonymous) @ WebVisu.dev.js:1
favicon.ico:1 GET http://192.168.1.5/favicon.ico 404 (Not Found)
```

Firefox display the visu and in the console there is:
```
Loading failed for the <script> with source “http://192.168.1.5/plc/WebVisu.dev.js”. webvisu.html:10:1
The script from “http://192.168.1.5/plc/WebVisu.dev.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type. webvisu.html
```

What browser compability is expected ?

**Comment by tnentwig** [comment]
Hi,

the SPA uses language constructs of ECMAScript 6 (ES6, Javascript standard) which are supported by modern browsers like Firefox, Chrome or Edge. The IE11 does not display the visu as it only supports ES5. From my point of view there is no need to support IE11, because it shouldn't be used anymore: [https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/](https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/)
Or do you see a reason? 

But your visualisations are displayed correctly in firefox and chrome? The logs above can be ignored. I will catch them in future releases.

**Comment by Ekristoffe** [comment]
I was just wondering.
I haven't tested Edge (since it is chromium based I don't think it should be so much different from chrome)

**Comment by tnentwig** [comment]
Yes, its quite the same. Thanks you for your note, I have just added the required browser into the readme.
