### ISSUE TITLE
Browser cache

### ISSUE THREAD

**Issue by goodspeed1986** [tnentwig/WebVisu#6]
I have problems with adding new elements to webVisu, because browser cache old one. When I open a new incognition window it works fine only first time, then I need open another one.

**Comment by Ekristoffe** [comment]
Hello, What browser are you using ?

**Comment by tnentwig** [comment]
Hi, this is actually the expected behavior. The webvisu use the download-id of the visu-ini.xml to check if the visualisations have changed. All xml files will be reloaded if this id changed. Codesys changes the download-id unfortunately only on download, but not on online change.
I will try to improve this in later versions.
